BigFloat compatibility for qr_jacobimatrix
JuliaApproximation/ClassicalOrthogonalPolynomials.jl pull request #146
Opened 2023-07-26 18:23 UTC by TSGut

@dlfivefifty @MikaelSlevinsky  This PR restores BigFloat compatibility to the QR variants of jacobimatrix computation. The fix in theory also addresses Cholesky but that remains broken because of a similar issue in InfiniteLinearAlgebra.jl exemplified by 

```julia
julia> P = Normalized(legendre(big(0)..big(1)))
Normalized(Legendre{BigFloat}() affine mapped to 0..1)

julia> X = jacobimatrix(P)
ℵ₀×ℵ₀ LazyBandedMatrices.SymTridiagonal{BigFloat, Fill{BigFloat, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, BroadcastVector{BigFloat, typeof(sqrt), Tuple{BroadcastVector{BigFloat, typeof(*), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}, BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}}}}}} with indices OneToInf()×OneToInf():
 0.5       0.288675   ⋅         ⋅         ⋅         ⋅         ⋅         ⋅       …  
 0.288675  0.5       0.258199   ⋅         ⋅         ⋅         ⋅         ⋅          
  ⋅        0.258199  0.5       0.253546   ⋅         ⋅         ⋅         ⋅          
  ⋅         ⋅        0.253546  0.5       0.251976   ⋅         ⋅         ⋅          
  ⋅         ⋅         ⋅        0.251976  0.5       0.251259   ⋅         ⋅          
  ⋅         ⋅         ⋅         ⋅        0.251259  0.5       0.250873   ⋅       …  
  ⋅         ⋅         ⋅         ⋅         ⋅        0.250873  0.5       0.25064     
  ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        0.25064   0.5         
  ⋅         ⋅         ⋅         ⋅         ⋅         ⋅         ⋅        0.25049     
 ⋮                                                 ⋮                            ⋱  

julia> cholesky(Symmetric(X^2)).U[1,1]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
  [1] getindex
    @ ./essentials.jl:14 [inlined]
  [2] getindex
    @ ./subarray.jl:286 [inlined]
  [3] _getindex
    @ ./abstractarray.jl:1344 [inlined]
  [4] getindex
    @ ./abstractarray.jl:1294 [inlined]
  [5] macro expansion
    @ ~/Documents/Backends/julia-1.9.0/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:221 [inlined]
  [6] macro expansion
    @ ./simdloop.jl:77 [inlined]
  [7] lmul!(s::BigFloat, X::SubArray{BigFloat, 2, Matrix{BigFloat}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false})
    @ LinearAlgebra ~/Documents/Backends/julia-1.9.0/share/julia/stdlib/v1.9/LinearAlgebra/src/generic.jl:220
  [8] _banded_lmul!
    @ ~/.julia/packages/BandedMatrices/qLIMl/src/generic/broadcast.jl:938 [inlined]
  [9] banded_lmul!
    @ ~/.julia/packages/BandedMatrices/qLIMl/src/generic/broadcast.jl:947 [inlined]
 [10] materialize!
    @ ~/.julia/packages/BandedMatrices/qLIMl/src/generic/broadcast.jl:950 [inlined]
 [11] #lmul!#10
    @ ~/.julia/packages/ArrayLayouts/3K92Y/src/lmul.jl:47 [inlined]
 [12] lmul!
    @ ~/.julia/packages/ArrayLayouts/3K92Y/src/lmul.jl:47 [inlined]
 [13] default_blasmul!(α::BigFloat, A::Adjoint{BigFloat, SubArray{BigFloat, 2, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}}, B::SubArray{BigFloat, 2, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, β::BigFloat, C::SubArray{BigFloat, 2, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false})
    @ ArrayLayouts ~/.julia/packages/ArrayLayouts/3K92Y/src/muladd.jl:172
 [14] materialize!(M::ArrayLayouts.MulAdd{BandedMatrices.BandedRows{ArrayLayouts.DenseColumnMajor}, BandedMatrices.BandedColumns{ArrayLayouts.DenseColumnMajor}, BandedMatrices.BandedColumns{ArrayLayouts.DenseColumnMajor}, BigFloat, Adjoint{BigFloat, SubArray{BigFloat, 2, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}}, SubArray{BigFloat, 2, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, SubArray{BigFloat, 2, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}})
    @ ArrayLayouts ~/.julia/packages/ArrayLayouts/3K92Y/src/muladd.jl:241
 [15] muladd!
    @ ~/.julia/packages/ArrayLayouts/3K92Y/src/muladd.jl:70 [inlined]
 [16] partialcholesky!(F::InfiniteLinearAlgebra.AdaptiveCholeskyFactors{BigFloat, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, ApplyArray{BigFloat, 2, typeof(*), Tuple{LazyBandedMatrices.SymTridiagonal{BigFloat, Fill{BigFloat, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, BroadcastVector{BigFloat, typeof(sqrt), Tuple{BroadcastVector{BigFloat, typeof(*), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}, BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}}}}}}, LazyBandedMatrices.SymTridiagonal{BigFloat, Fill{BigFloat, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, BroadcastVector{BigFloat, typeof(sqrt), Tuple{BroadcastVector{BigFloat, typeof(*), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}, BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}}}}}}}}}, n::Int64)
    @ InfiniteLinearAlgebra ~/.julia/packages/InfiniteLinearAlgebra/y1GuF/src/infcholesky.jl:35
 [17] getindex(F::InfiniteLinearAlgebra.AdaptiveCholeskyFactors{BigFloat, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, ApplyArray{BigFloat, 2, typeof(*), Tuple{LazyBandedMatrices.SymTridiagonal{BigFloat, Fill{BigFloat, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, BroadcastVector{BigFloat, typeof(sqrt), Tuple{BroadcastVector{BigFloat, typeof(*), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}, BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}}}}}}, LazyBandedMatrices.SymTridiagonal{BigFloat, Fill{BigFloat, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, BroadcastVector{BigFloat, typeof(sqrt), Tuple{BroadcastVector{BigFloat, typeof(*), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}, BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}}}}}}}}}, k::Int64, j::Int64)
    @ InfiniteLinearAlgebra ~/.julia/packages/InfiniteLinearAlgebra/y1GuF/src/infcholesky.jl:42
 [18] getindex(A::UpperTriangular{BigFloat, InfiniteLinearAlgebra.AdaptiveCholeskyFactors{BigFloat, BandedMatrix{BigFloat, Matrix{BigFloat}, Base.OneTo{Int64}}, ApplyArray{BigFloat, 2, typeof(*), Tuple{LazyBandedMatrices.SymTridiagonal{BigFloat, Fill{BigFloat, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}, BroadcastVector{BigFloat, typeof(sqrt), Tuple{BroadcastVector{BigFloat, typeof(*), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tuple{InfiniteArrays.InfStepRange{BigFloat, BigFloat}, InfiniteArrays.InfStepRange{Int64, Int64}}}, BigFloat}}, BroadcastVector{BigFloat, typeof(/), Tuple{BroadcastVector{BigFloat, typeof(/), Tupl [...]

2023-07-26 20:18 UTC, TSGut commented
Ok @dlfivefifty , after some digging: the error above for Cholesky appears to live in this line https://github.com/JuliaLinearAlgebra/InfiniteLinearAlgebra.jl/blob/0fc35261c6e8a8ce2bb4b647cbf935855e4b81ec/src/infcholesky.jl#L35

ArrayLayouts fails to materialize MulAdd for certain BigFloat matrices. I can avoid this by special casing the line including muladd!() to just to the lazy multiplication `α * A * B + β C` for `T==BigFloat` without the fancy BLAS-like machinery. Any alternative ideas I am missing before I do that?

( btw which entry does muladd!() overwrite? is it `A`? the docs are a bit unclear at https://github.com/JuliaLinearAlgebra/ArrayLayouts.jl/blob/master/src/muladd.jl )

2023-07-27 15:37 UTC, dlfivefifty commented
🤷‍♂️ I can't find the code where I had to work around this. But definitely don't specialise to `T == BigFloat`, just use `isprimitivetype`

2023-07-27 15:38 UTC, dlfivefifty requested changes

2023-07-27 15:38 UTC, dlfivefifty commented on src/choleskyQR.jl
> +    if T == BigFloat
This is silly since its just 2. Just use `zeros(T,2)`

2023-07-30 15:19 UTC, dlfivefifty commented on src/choleskyQR.jl
> +    dv = zeros(T,2)
Try not to add extra spaces to ends of lines

2023-07-30 15:19 UTC, merged