WIP: Speed up Cholesky Jacobi matrices
JuliaApproximation/ClassicalOrthogonalPolynomials.jl pull request #169
Opened 2024-01-21 22:23 UTC by TSGut

WIP to address https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl/issues/167. It will also fix some docstring issues.

For now a lot of speed is gained by creating a dedicated method for getindex of `Symmetric{Clenshaw}`, `CholeskyJacobiData` as well as better resizing in `cholesky_jacobimatrix`. 

For low polynomial degree the method is approaching acceptable speeds again, though even with Symmetric Clenshaw now as fast as regular Clenshaw the Clenshaw evals are still a major bottleneck:
```julia
julia> P = Normalized(Legendre());
julia> x = axes(P,1);
julia> J = jacobimatrix(P);
julia> wf(x) = (2 .+ x.^4);
julia> W = Symmetric(P \ (wf.(x) .* P));
# raw Clenshaw timing
julia> @time W[1:1000,1:1000];
  0.027092 seconds (18 allocations: 485.281 KiB)
# Cholesky X timing
julia> Jchol = cholesky_jacobimatrix(W, P);
julia> @time Jchol[1:1000,1:1000];
  0.061909 seconds (4.57 k allocations: 8.131 MiB)
```

Of course for high polynomial degree this causes major slow downs, although there are clearly also other things to optimize:
```julia
julia> r = 0.5;
julia> lmin, lmax = (1-sqrt(r))^2,  (1+sqrt(r))^2;
julia> P = Normalized(chebyshevu(lmin..lmax));
julia> x = axes(P,1);
julia> J = jacobimatrix(P);
julia> wf(x) = 1/(x*r);
# raw Clenshaw timing
julia> W = Symmetric(P \ (wf.(x) .* P));
julia> @time W[1:1000,1:1000];
  3.562982 seconds (18 allocations: 10.764 MiB)
# Cholesky X timing
julia> Jchol = cholesky_jacobimatrix(W, P);
julia> @time Jchol[1:1000,1:1000];
  5.413114 seconds (4.60 k allocations: 19.039 MiB)
```

Todo list:

- [ ] Also make changes for QR method once Cholesky is satisfactory
- [ ] While symmetric and non-symmetric Clenshaw are now equal in speed, Clenshaw evaluation is still very slow which constitutes 80%+ of the compute time spent in `cholesky_jacobimatrix`.
- [ ] Add tests

2024-01-22 07:49 UTC, TSGut commented
Ok, like I said based on profiling and benchmarking the remaining cost is in evaluating the Clenshaw matrix and performing its Cholesky decompositions.

(I still need to add tests and make tests pass, so not ready for merge yet)

@dlfivefifty How do you want to proceed with this? Is there hope for speeding up Clenshaw or the Cholesky of a Clenshaw? If not then I think this is bottlenecked at the speed of this PR.

To be fair, the computation is fast for weight modifications of low to medium degree weights, just not high degree where Clenshaw starts to struggle. We can to a 1 million size Jacobi matrix sized block in under a second for a degree 2 weight:
```julia
julia> P = Normalized(Legendre());

julia> x = axes(P,1);

julia> J = jacobimatrix(P);

julia> wf2(x) = (2 .+ x.^2);

julia> W2 = Symmetric(P \ (wf2.(x) .* P));

julia> Jchol2 = cholesky_jacobimatrix(W2, P);

julia> @time Jchol2[1:1000000,1:1000000];
  0.762198 seconds (16.00 M allocations: 1.103 GiB, 5.34% gc time)
```

Barring Clenshaw and Cholesky speed-ups, I suspect implementing the rational case is the next best thing.

2024-01-22 12:07 UTC, dlfivefifty commented
That speed looks fine

2024-01-23 07:20 UTC, TSGut commented
@dlfivefifty Ok this is ready for merge or review. The patch coverage is 100%.

2024-02-07 09:39 UTC, dlfivefifty requested changes

2024-02-07 09:39 UTC, dlfivefifty commented on src/clenshaw.jl
> +function getindex(S::Symmetric{T,<:Clenshaw{<:Any}}, k::Integer, jr::AbstractUnitRange) where T
```suggestion
function getindex(S::Symmetric{T,<:Clenshaw}, k::Integer, jr::AbstractUnitRange) where T
```

2024-02-07 09:39 UTC, dlfivefifty commented on src/clenshaw.jl
> +function getindex(S::Symmetric{T,<:Clenshaw{<:Any}}, kr::AbstractUnitRange, j::Integer) where T
```suggestion
function getindex(S::Symmetric{T,<:Clenshaw}, kr::AbstractUnitRange, j::Integer) where T
```

2024-02-07 09:39 UTC, dlfivefifty commented on src/clenshaw.jl
> +function getindex(S::Symmetric{T,<:Clenshaw{<:Any}}, kr::AbstractUnitRange, jr::AbstractUnitRange) where T
```suggestion
function getindex(S::Symmetric{T,<:Clenshaw{<:Any}}, kr::AbstractUnitRange, jr::AbstractUnitRange) where T
```

2024-02-07 09:40 UTC, dlfivefifty approved these changes

2024-02-07 19:44 UTC, merged